These MultiInterpolation functions GriddedDataReporter
idaholab/isopod pull request #48
Opened 2022-08-04 23:57 UTC by lynnmunday

closes #47

2022-08-05 00:06 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1131284/) on 4dd1584 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/isopod/docs/PRs/48/site)

This comment will be updated on new commits.

2022-08-05 00:10 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1131288/) on 4dd1584 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6a10dd</th>
      <th colspan=4>#48 4dd158</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>87.22%</td>
      <td>86.76%</td>
      <td>-0.46%</td>
      <td>77.27%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>771</td>
      <td>773</td>
      <td>+2</td>
      <td>17</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>113</td>
      <td>118</td>
      <td>+5</td>
      <td>5</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/isopod/docs/PRs/48/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/isopod/docs/PRs/48/coverage)

## Warnings

- New new line coverage rate 77.27% is less than the suggested 90.0%



This comment will be updated on new commits.

2022-08-05 03:39 UTC, lynnmunday commented
@aaelmeli will you look at this.  @zachmprince Will you review this too

2022-08-06 04:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1133155/) on e9c0196 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/isopod/docs/PRs/48/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/isopod/docs/PRs/48/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 6a10dd0962a03aab372ce99d2e4c2e4a1f856835`

2022-08-06 18:46 UTC, lynnmunday commented
@aaelmeli would you review this?

2022-08-06 18:55 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1133545/) on 8dbb7a5 wanted to post the following:


The following coverage requirement(s) failed:
- Coverage rate 84.68% is less than the required 85.0%

2022-08-07 20:51 UTC, aaelmeli requested changes
Can we add some example where the parameter values is supplied by some reporter that is different that the reporter that supplies the grids, etc.

2022-08-08 15:22 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1133545/) on 8dbb7a5 wanted to post the following:


The following coverage requirement(s) failed:
- Coverage rate 84.68% is less than the required 85.0%

2022-08-08 16:39 UTC, lynnmunday commented on src/functions/PiecewiseMultiInterpolationFromReporter.C
> +                                        "reporter containing value for each point in the grid.  "
I wanted it to be clear that the function values can from any reporter and not just those read in by the griddedDataReporter

2022-08-08 21:57 UTC, merged