Add elastic inversion capability using batch materials
idaholab/isopod pull request #78
Opened 2023-06-27 23:12 UTC by dewenyushu

Refs #77

2023-06-27 23:20 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1623841/) on 6198c48 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/isopod/docs/PRs/78/site)

This comment will be updated on new commits.

2023-06-27 23:21 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1623845/) on 6198c48 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>3d719b</th>
      <th colspan=4>#78 6198c4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>80.54%</td>
      <td>82.54%</td>
      <td>+2.00%</td>
      <td>96.77%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>178</td>
      <td>208</td>
      <td>+30</td>
      <td>30</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>43</td>
      <td>44</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/isopod/docs/PRs/78/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/isopod/docs/PRs/78/coverage)



This comment will be updated on new commits.

2023-06-28 16:12 UTC, dewenyushu commented
> This looks good. Were there any code changes from the blackbear pr?

Not really :) only changing the object registration from `blackbearApp` to `IsopodApp`

2023-06-28 23:04 UTC, lynnmunday requested changes
one small change and then I'll merge it.

2023-06-29 04:04 UTC, dewenyushu commented on test/tests/bimaterial_elastic_inversion_batch_mat/grad.i
> +    execution_order_group = -1 # need to make sure that the UO executes before the VPP
Neat

2023-06-29 15:12 UTC, merged